name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia 00:00 UTC
  workflow_dispatch:       # permite rodar manualmente

# ⬇️ dá permissão de escrita pro GITHUB_TOKEN
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: GuiTorX         # seu username
          outputs: dist/snake.svg           # gera o arquivo

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output             # branch onde ficará o SVG
          build_dir: dist                   # pasta com o arquivo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
